# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
email: webteam@canonical.com
description: Deployments so easy it's almost magical.
baseurl: ""
asset_path: https://assets.ubuntu.com/v1/
navigation:
- text: Home
  url: /
exclude: [
  'LICENCE',
  'README.md',
  'gulpfile.babel.js',
  'package.json',
  'node_modules'
]
permalink: /:title

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# only build incrementally
incremental: true
